# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SheltasksCliNightly < Formula
  desc "Sheltasks (Nightly): My CLI friend helping me with my daily tasks"
  homepage "https://github.com/vedantmgoyal9/vedantmgoyal9"
  version "1.1.0-nightly"
  license "MIT"

  depends_on "msitools"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_darwin_arm64.tar.gz"
      sha256 "ebb736c90a754b143e7703d95719a5c232fee3530a9d97856d2d026f6484bc1a"

      def install
        bin.install "sheltasks-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_amd64.tar.gz"
        sha256 "9680caf338ea991ab1dc6dc26e7ead906a6f86b0dc467734b286440b530f301d"

        def install
          bin.install "sheltasks-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_arm64.tar.gz"
        sha256 "d5e7e59b47bb1f63073678deccbf1ddae20281015bb7b50285e0130503a8a055"

        def install
          bin.install "sheltasks-cli"
        end
      end
    end
  end

  conflicts_with "sheltasks-cli"
end
