# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SheltasksCliNightly < Formula
  desc "Sheltasks (Nightly): My CLI friend helping me with my daily tasks"
  homepage "https://github.com/vedantmgoyal9/vedantmgoyal9"
  version "1.1.0-nightly"
  license "MIT"

  depends_on "msitools"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_darwin_arm64.tar.gz"
      sha256 "0a5b7cbb9c6b84e3ab97a63febe615bc56aef0ca6ac0eee5a958ee9d67acc5b2"

      def install
        bin.install "sheltasks-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_amd64.tar.gz"
        sha256 "45a13e8e140f334a96a2ccc03baadf4b916f21bf4e0da6484323fa99e38ba704"

        def install
          bin.install "sheltasks-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_arm64.tar.gz"
        sha256 "a600ce98ef4f6c2ece49ed468bd576d5d2f4a65b10a879cad6ee64c827dc8b48"

        def install
          bin.install "sheltasks-cli"
        end
      end
    end
  end

  conflicts_with "sheltasks-cli"
end
