# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SheltasksCliNightly < Formula
  desc "Sheltasks (Nightly): My CLI friend helping me with my daily tasks"
  homepage "https://github.com/vedantmgoyal9/vedantmgoyal9"
  version "1.1.0-nightly"
  license "MIT"

  depends_on "msitools"

  on_macos do
    on_arm do
      url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_darwin_arm64.tar.gz"
      sha256 "6aec72d8e29cceb120f12793feb643c89931dcb0afdac374fce24afc7b106f8c"

      def install
        bin.install "sheltasks-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_amd64.tar.gz"
        sha256 "fddf3c40a26fb54968e443d4db3813f09fa09780f44154e3b07717ebcd3fbd09"

        def install
          bin.install "sheltasks-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_arm64.tar.gz"
        sha256 "8136d03acd7d166c3d1d754b167ba7f38b605156ae026941f8c7357270db789a"

        def install
          bin.install "sheltasks-cli"
        end
      end
    end
  end

  conflicts_with "sheltasks-cli"
end
