.TH GCAB "1" "December 2012" "gcab v1.6"
.SH NAME
gcab \- Program to create Microsoft cabinet (.cab) archives
.SH SYNOPSIS
.B gcab
[\fIOPTION\fR]... \fICABFILE\fR \fIFILES...\fR
.SH DESCRIPTION
.PP
Create the cabinet file CABFILE from the list of FILES.
.SH OPTIONS
.TP
\fB\-c, --create\fR
create a new cabinet archive
.TP
\fB\-x, --extract\fR
extract files from a cabinet archive
.TP
\fB\-t, --list\fR
list files of a cabinet archive
.TP
\fB\-n, --nopath\fR
create files without pathnames
.TP
\fB\-C, --directory DIR\fR
change or extract to directory DIR
.TP
\fB\-v, --verbose\fR
verbosely list files processed
.TP
\fB\-z, --zip\fR
use zip compression
.SH AUTHOR
Written by Marc-André Lureau <marcandre.lureau@gmail.com>.

.SH "SEE ALSO"
.TP
\fBcabextract\fR(1)
program to extract files from Microsoft cabinet (.cab) archives
