# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SheltasksCliNightly < Formula
  desc "Sheltasks (Nightly): My CLI friend helping me with my daily tasks"
  homepage "https://github.com/vedantmgoyal9/vedantmgoyal9"
  version "1.1.0-nightly"
  license "MIT"

  depends_on "msitools"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_darwin_arm64.tar.gz"
      sha256 "dab9364b832d3c56bf120e122c57b1f0e1c6cd7e6c839c0d59eb6f21d644af4c"

      def install
        bin.install "sheltasks-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_amd64.tar.gz"
      sha256 "2bef759027fdb9c9df633959f4c9d2e8d3cc113af0ded77ed144ef9bdc9dca22"

      def install
        bin.install "sheltasks-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_arm64.tar.gz"
      sha256 "211ed242fbcc6bb773d718011d7a29cd8f2145781a326ed36d9e6ce71c1ea37e"

      def install
        bin.install "sheltasks-cli"
      end
    end
  end

  conflicts_with "sheltasks-cli"
end
