# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SheltasksCliNightly < Formula
  desc "Sheltasks (Nightly): My CLI friend helping me with my daily tasks"
  homepage "https://github.com/vedantmgoyal9/vedantmgoyal9"
  version "1.1.0-nightly"
  license "MIT"

  depends_on "msitools"

  on_macos do
    on_arm do
      url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_darwin_arm64.tar.gz"
      sha256 "eb017aae8d4d13ec077f42735a57177e689ed459011dd8e286c659064622e2f4"

      def install
        bin.install "sheltasks-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_amd64.tar.gz"
      sha256 "9893856a55db0296c77215f4400ebb4a4dc8db06da018b1c7d7b2db5d78ae1b5"

      def install
        bin.install "sheltasks-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vedantmgoyal9/vedantmgoyal9/releases/download/sheltasks-cli/nightly/sheltasks-cli_linux_arm64.tar.gz"
      sha256 "144de4b443f18ba3a62d5bd93d58462e175d9ff2644d3a81c4776381f4930301"

      def install
        bin.install "sheltasks-cli"
      end
    end
  end

  conflicts_with "sheltasks-cli"
end
